name: Setup
description: 'Installs node, driver dependencies, and builds source'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install -g npm@latest
      shell: bash
    - run: npm clean-install
      shell: bash
    - uses: mongodb-labs/drivers-github-tools/garasign/setup@main
      with: 
        garasign_username: 'aditi.khare' #${{ secrets.GRS_CONFIG_USER1_USERNAME }}
        garasign_password: 'passwordabc' #${{ secrets.GRS_CONFIG_USER1_PASSWORD }}
        artifactory_username: 'username' #${{ secrets.ARTIFACTORY_USER }}
        artifactory_password: 'password123' #${{ secrets.ARTIFACTORY_PASSWORD }}  
