sudo: false
dist: trusty

language: node_js
node_js:
  - 6
  - 8
  - 10

cache:
  yarn: true
  directories:
    - node_modules

script:
  - npm run-script test-node
  - if [[ $(node --version) != v4* ]] ; then npm run-script test-browser; fi