sudo: required 
dist: trusty

language: node_js

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: tests
      node_js: 4
      env: MONGODB_VERSION=2.6.x
    - stage: tests
      node_js: 4
      env: MONGODB_VERSION=3.0.x
    - stage: tests
      node_js: 4
      env: MONGODB_VERSION=3.2.x
    - stage: tests
      node_js: 4
      env: MONGODB_VERSION=3.4.x
    - stage: tests
      node_js: 4
      env: MONGODB_VERSION=3.5.x

    - stage: tests
      node_js: 6
      env: MONGODB_VERSION=3.4.x
    - stage: tests
      node_js: 8
      env: MONGODB_VERSION=3.4.x
