sudo: false
dist: trusty

language: node_js
node_js:
  - 4
  - 6
  - 8
  - 10

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

script:
  - npm run-script test-node
  - if [[ $(node --version) != v4* ]] ; then npm run-script test-browser; fi
