sudo: false
dist: trusty

language: node_js

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - 4
  - 6
  - 8
  - 10

  script:
  - npm run lint && npm run test-node
  - if [[ $(node --version) != v4* ]] ; then npm run-script test-browser; fi
