sudo: false
dist: trusty

language: node_js

cache:
  yarn: true
  directories:
    - node_modules

before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
    - "npm run build"

node_js:
  - 4
  - 6
  - 8
  - 10
