name: Compress and Sign
description: 'Compresses package and signs with garasign'

inputs: 
    garasign_username:
      required: true
    garasign_password:
      required: true
    artifactory_username:
      required: true
    artifactory_password:
      required: true

runs:
  using: composite
  steps:
    - run: npm pack
      shell: bash
    - name: Get release version and release package file name
      id: vars
      run: |
        package_version=$(jq --raw-output '.version' package.json)
        echo "package_version=${package_version}" >> "$GITHUB_OUTPUT"
        echo "package_file=bson-${package_version}.tgz" >> "$GITHUB_OUTPUT"
    - name: Create detached signature
      uses: mongodb-labs/drivers-github-tools/garasign/gpg-sign@v1
      with:
        filenames: ${{ steps.vars.package_file }}
        garasign_username: ${{ inputs.garasign_username }}
        garasign_password: ${{ inputs.garasign_password }}
        artifactory_username: ${{ inputs.artifactory_username }}
        artifactory_password: ${{ inputs.artifactory_password }}
    - if: false
      name: "Upload release artifacts"
      run: gh release upload v${{ steps.vars.package_version }} ${{ steps.vars.package_file }}.sig