name: Compress and Sign
description: 'Compresses package and signs with garasign'

inputs: 
    garasign_username:
      description: 'Garasign username input for drivers-github-tools/garasign/gpg-sign'
      required: true
    garasign_password:
      description: 'Garasign password input for drivers-github-tools/garasign/gpg-sign'
      required: true
    artifactory_username:
      description: 'Artifactory username input for drivers-github-tools/garasign/gpg-sign'
      required: true
    artifactory_password:
      description: 'Artifactory password input for drivers-github-tools/garasign/gpg-sign'
      required: true

runs:
  using: composite
  steps:
    - run: npm pack
      shell: bash

    - name: Get release version and release package file name
      id: vars
      shell: bash
      run: |
        package_version=$(jq --raw-output '.version' package.json)
        echo "package_version=${package_version}" >> "$GITHUB_OUTPUT"
        echo "package_file=bson-${package_version}.tgz" >> "$GITHUB_OUTPUT"

    - name: Set up drivers-github-tools
      uses: mongodb-labs/drivers-github-tools/setup@v2
      with: 
        aws_role_arn: ${{ inputs.aws_role_arn }}
        aws_region_name: ${{ inputs.aws_region_name }}
        aws_secret_id: ${{ inputs.aws_secret_id }}
    - name: Create detached signature
      uses: mongodb-labs/drivers-github-tools/gpg-sign@v2
    - name: "Temporary: check that signature exists"
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.vars.outputs.package_version }}
        path: |
          ${{ steps.vars.outputs.package_file }}
          ${{ steps.vars.outputs.package_filen }}.sig
        retention-days: 3
    # - name: "Upload release artifacts"
    #   run: gh release upload v${{ steps.vars.outputs.package_version }} ${{ steps.vars.outputs.package_file }}.sig
    #   shell: bash
    #   env:
    #     GH_TOKEN: ${{ github.token }}