on:
  push:
    branches: [5.x]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write
  id-token: write

name: release-5x

jobs:
  release_please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v4
        with:
          target-branch: 5.x
  
  compress-sign-and-upload:
    needs: [release_please]
    if: ${{ needs.release_please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: actions/setup
        uses: ./.github/actions/setup
      - name: actions/compress_sign_and_upload
        uses: ./.github/actions/compress_sign_and_upload
      - if: false
        run: npm publish --provenance --tag=5x
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
